services:
  postgres:
    image: postgres:17-alpine
    ports:
      - ${PORT}:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
