// Code generated by mockery v2.46.3. DO NOT EDIT.

package handlersmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storystructurev1 "buf.build/gen/go/a-novel/proto/protocolbuffers/go/storystructure/v1"
)

// MockCreateBeat is an autogenerated mock type for the CreateBeat type
type MockCreateBeat struct {
	mock.Mock
}

type MockCreateBeat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCreateBeat) EXPECT() *MockCreateBeat_Expecter {
	return &MockCreateBeat_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockCreateBeat) Exec(_a0 context.Context, _a1 *storystructurev1.CreateBeatServiceExecRequest) (*storystructurev1.CreateBeatServiceExecResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *storystructurev1.CreateBeatServiceExecResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *storystructurev1.CreateBeatServiceExecRequest) (*storystructurev1.CreateBeatServiceExecResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *storystructurev1.CreateBeatServiceExecRequest) *storystructurev1.CreateBeatServiceExecResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storystructurev1.CreateBeatServiceExecResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *storystructurev1.CreateBeatServiceExecRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCreateBeat_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockCreateBeat_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *storystructurev1.CreateBeatServiceExecRequest
func (_e *MockCreateBeat_Expecter) Exec(_a0 interface{}, _a1 interface{}) *MockCreateBeat_Exec_Call {
	return &MockCreateBeat_Exec_Call{Call: _e.mock.On("Exec", _a0, _a1)}
}

func (_c *MockCreateBeat_Exec_Call) Run(run func(_a0 context.Context, _a1 *storystructurev1.CreateBeatServiceExecRequest)) *MockCreateBeat_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storystructurev1.CreateBeatServiceExecRequest))
	})
	return _c
}

func (_c *MockCreateBeat_Exec_Call) Return(_a0 *storystructurev1.CreateBeatServiceExecResponse, _a1 error) *MockCreateBeat_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCreateBeat_Exec_Call) RunAndReturn(run func(context.Context, *storystructurev1.CreateBeatServiceExecRequest) (*storystructurev1.CreateBeatServiceExecResponse, error)) *MockCreateBeat_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCreateBeat creates a new instance of MockCreateBeat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreateBeat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreateBeat {
	mock := &MockCreateBeat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
