// Code generated by mockery v2.46.3. DO NOT EDIT.

package handlersmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storystructurev1 "buf.build/gen/go/a-novel/proto/protocolbuffers/go/storystructure/v1"
)

// MockGetPlotPoint is an autogenerated mock type for the GetPlotPoint type
type MockGetPlotPoint struct {
	mock.Mock
}

type MockGetPlotPoint_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetPlotPoint) EXPECT() *MockGetPlotPoint_Expecter {
	return &MockGetPlotPoint_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockGetPlotPoint) Exec(_a0 context.Context, _a1 *storystructurev1.GetPlotPointServiceExecRequest) (*storystructurev1.GetPlotPointServiceExecResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *storystructurev1.GetPlotPointServiceExecResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *storystructurev1.GetPlotPointServiceExecRequest) (*storystructurev1.GetPlotPointServiceExecResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *storystructurev1.GetPlotPointServiceExecRequest) *storystructurev1.GetPlotPointServiceExecResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storystructurev1.GetPlotPointServiceExecResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *storystructurev1.GetPlotPointServiceExecRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetPlotPoint_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetPlotPoint_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *storystructurev1.GetPlotPointServiceExecRequest
func (_e *MockGetPlotPoint_Expecter) Exec(_a0 interface{}, _a1 interface{}) *MockGetPlotPoint_Exec_Call {
	return &MockGetPlotPoint_Exec_Call{Call: _e.mock.On("Exec", _a0, _a1)}
}

func (_c *MockGetPlotPoint_Exec_Call) Run(run func(_a0 context.Context, _a1 *storystructurev1.GetPlotPointServiceExecRequest)) *MockGetPlotPoint_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storystructurev1.GetPlotPointServiceExecRequest))
	})
	return _c
}

func (_c *MockGetPlotPoint_Exec_Call) Return(_a0 *storystructurev1.GetPlotPointServiceExecResponse, _a1 error) *MockGetPlotPoint_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetPlotPoint_Exec_Call) RunAndReturn(run func(context.Context, *storystructurev1.GetPlotPointServiceExecRequest) (*storystructurev1.GetPlotPointServiceExecResponse, error)) *MockGetPlotPoint_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetPlotPoint creates a new instance of MockGetPlotPoint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetPlotPoint(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetPlotPoint {
	mock := &MockGetPlotPoint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
