// Code generated by mockery v2.46.3. DO NOT EDIT.

package handlersmocks

import (
	context "context"

	emptypb "google.golang.org/protobuf/types/known/emptypb"

	mock "github.com/stretchr/testify/mock"

	storystructurev1 "buf.build/gen/go/a-novel/proto/protocolbuffers/go/storystructure/v1"
)

// MockDeleteBeat is an autogenerated mock type for the DeleteBeat type
type MockDeleteBeat struct {
	mock.Mock
}

type MockDeleteBeat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteBeat) EXPECT() *MockDeleteBeat_Expecter {
	return &MockDeleteBeat_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockDeleteBeat) Exec(_a0 context.Context, _a1 *storystructurev1.DeleteBeatServiceExecRequest) (*emptypb.Empty, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *storystructurev1.DeleteBeatServiceExecRequest) (*emptypb.Empty, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *storystructurev1.DeleteBeatServiceExecRequest) *emptypb.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *storystructurev1.DeleteBeatServiceExecRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeleteBeat_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDeleteBeat_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *storystructurev1.DeleteBeatServiceExecRequest
func (_e *MockDeleteBeat_Expecter) Exec(_a0 interface{}, _a1 interface{}) *MockDeleteBeat_Exec_Call {
	return &MockDeleteBeat_Exec_Call{Call: _e.mock.On("Exec", _a0, _a1)}
}

func (_c *MockDeleteBeat_Exec_Call) Run(run func(_a0 context.Context, _a1 *storystructurev1.DeleteBeatServiceExecRequest)) *MockDeleteBeat_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storystructurev1.DeleteBeatServiceExecRequest))
	})
	return _c
}

func (_c *MockDeleteBeat_Exec_Call) Return(_a0 *emptypb.Empty, _a1 error) *MockDeleteBeat_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeleteBeat_Exec_Call) RunAndReturn(run func(context.Context, *storystructurev1.DeleteBeatServiceExecRequest) (*emptypb.Empty, error)) *MockDeleteBeat_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteBeat creates a new instance of MockDeleteBeat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteBeat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteBeat {
	mock := &MockDeleteBeat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
