// Code generated by mockery v2.46.3. DO NOT EDIT.

package handlersmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	storystructurev1 "buf.build/gen/go/a-novel/proto/protocolbuffers/go/storystructure/v1"
)

// MockListPlotPoints is an autogenerated mock type for the ListPlotPoints type
type MockListPlotPoints struct {
	mock.Mock
}

type MockListPlotPoints_Expecter struct {
	mock *mock.Mock
}

func (_m *MockListPlotPoints) EXPECT() *MockListPlotPoints_Expecter {
	return &MockListPlotPoints_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: _a0, _a1
func (_m *MockListPlotPoints) Exec(_a0 context.Context, _a1 *storystructurev1.ListPlotPointsServiceExecRequest) (*storystructurev1.ListPlotPointsServiceExecResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *storystructurev1.ListPlotPointsServiceExecResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *storystructurev1.ListPlotPointsServiceExecRequest) (*storystructurev1.ListPlotPointsServiceExecResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *storystructurev1.ListPlotPointsServiceExecRequest) *storystructurev1.ListPlotPointsServiceExecResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storystructurev1.ListPlotPointsServiceExecResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *storystructurev1.ListPlotPointsServiceExecRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockListPlotPoints_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockListPlotPoints_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *storystructurev1.ListPlotPointsServiceExecRequest
func (_e *MockListPlotPoints_Expecter) Exec(_a0 interface{}, _a1 interface{}) *MockListPlotPoints_Exec_Call {
	return &MockListPlotPoints_Exec_Call{Call: _e.mock.On("Exec", _a0, _a1)}
}

func (_c *MockListPlotPoints_Exec_Call) Run(run func(_a0 context.Context, _a1 *storystructurev1.ListPlotPointsServiceExecRequest)) *MockListPlotPoints_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storystructurev1.ListPlotPointsServiceExecRequest))
	})
	return _c
}

func (_c *MockListPlotPoints_Exec_Call) Return(_a0 *storystructurev1.ListPlotPointsServiceExecResponse, _a1 error) *MockListPlotPoints_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockListPlotPoints_Exec_Call) RunAndReturn(run func(context.Context, *storystructurev1.ListPlotPointsServiceExecRequest) (*storystructurev1.ListPlotPointsServiceExecResponse, error)) *MockListPlotPoints_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockListPlotPoints creates a new instance of MockListPlotPoints. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockListPlotPoints(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockListPlotPoints {
	mock := &MockListPlotPoints{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
