// Code generated by mockery v2.46.3. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	services "github.com/a-novel/uservice-story-structure/pkg/services"
	mock "github.com/stretchr/testify/mock"
)

// MockDeleteBeat is an autogenerated mock type for the DeleteBeat type
type MockDeleteBeat struct {
	mock.Mock
}

type MockDeleteBeat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeleteBeat) EXPECT() *MockDeleteBeat_Expecter {
	return &MockDeleteBeat_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, data
func (_m *MockDeleteBeat) Exec(ctx context.Context, data *services.DeleteBeatRequest) error {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *services.DeleteBeatRequest) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeleteBeat_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDeleteBeat_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - data *services.DeleteBeatRequest
func (_e *MockDeleteBeat_Expecter) Exec(ctx interface{}, data interface{}) *MockDeleteBeat_Exec_Call {
	return &MockDeleteBeat_Exec_Call{Call: _e.mock.On("Exec", ctx, data)}
}

func (_c *MockDeleteBeat_Exec_Call) Run(run func(ctx context.Context, data *services.DeleteBeatRequest)) *MockDeleteBeat_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*services.DeleteBeatRequest))
	})
	return _c
}

func (_c *MockDeleteBeat_Exec_Call) Return(_a0 error) *MockDeleteBeat_Exec_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeleteBeat_Exec_Call) RunAndReturn(run func(context.Context, *services.DeleteBeatRequest) error) *MockDeleteBeat_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeleteBeat creates a new instance of MockDeleteBeat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeleteBeat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeleteBeat {
	mock := &MockDeleteBeat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
