// Code generated by mockery v2.46.3. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	services "github.com/a-novel/uservice-story-structure/pkg/services"
	mock "github.com/stretchr/testify/mock"
)

// MockSearchPlotPoints is an autogenerated mock type for the SearchPlotPoints type
type MockSearchPlotPoints struct {
	mock.Mock
}

type MockSearchPlotPoints_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchPlotPoints) EXPECT() *MockSearchPlotPoints_Expecter {
	return &MockSearchPlotPoints_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, data
func (_m *MockSearchPlotPoints) Exec(ctx context.Context, data *services.SearchPlotPointsRequest) (*services.SearchPlotPointsResponse, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.SearchPlotPointsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services.SearchPlotPointsRequest) (*services.SearchPlotPointsResponse, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services.SearchPlotPointsRequest) *services.SearchPlotPointsResponse); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.SearchPlotPointsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services.SearchPlotPointsRequest) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchPlotPoints_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSearchPlotPoints_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - data *services.SearchPlotPointsRequest
func (_e *MockSearchPlotPoints_Expecter) Exec(ctx interface{}, data interface{}) *MockSearchPlotPoints_Exec_Call {
	return &MockSearchPlotPoints_Exec_Call{Call: _e.mock.On("Exec", ctx, data)}
}

func (_c *MockSearchPlotPoints_Exec_Call) Run(run func(ctx context.Context, data *services.SearchPlotPointsRequest)) *MockSearchPlotPoints_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*services.SearchPlotPointsRequest))
	})
	return _c
}

func (_c *MockSearchPlotPoints_Exec_Call) Return(_a0 *services.SearchPlotPointsResponse, _a1 error) *MockSearchPlotPoints_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchPlotPoints_Exec_Call) RunAndReturn(run func(context.Context, *services.SearchPlotPointsRequest) (*services.SearchPlotPointsResponse, error)) *MockSearchPlotPoints_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchPlotPoints creates a new instance of MockSearchPlotPoints. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchPlotPoints(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchPlotPoints {
	mock := &MockSearchPlotPoints{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
