// Code generated by mockery v2.46.3. DO NOT EDIT.

package servicesmocks

import (
	context "context"

	services "github.com/a-novel/uservice-story-structure/pkg/services"
	mock "github.com/stretchr/testify/mock"
)

// MockGetBeat is an autogenerated mock type for the GetBeat type
type MockGetBeat struct {
	mock.Mock
}

type MockGetBeat_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetBeat) EXPECT() *MockGetBeat_Expecter {
	return &MockGetBeat_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, data
func (_m *MockGetBeat) Exec(ctx context.Context, data *services.GetBeatRequest) (*services.GetBeatResponse, error) {
	ret := _m.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *services.GetBeatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *services.GetBeatRequest) (*services.GetBeatResponse, error)); ok {
		return rf(ctx, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *services.GetBeatRequest) *services.GetBeatResponse); ok {
		r0 = rf(ctx, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.GetBeatResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *services.GetBeatRequest) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetBeat_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockGetBeat_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - data *services.GetBeatRequest
func (_e *MockGetBeat_Expecter) Exec(ctx interface{}, data interface{}) *MockGetBeat_Exec_Call {
	return &MockGetBeat_Exec_Call{Call: _e.mock.On("Exec", ctx, data)}
}

func (_c *MockGetBeat_Exec_Call) Run(run func(ctx context.Context, data *services.GetBeatRequest)) *MockGetBeat_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*services.GetBeatRequest))
	})
	return _c
}

func (_c *MockGetBeat_Exec_Call) Return(_a0 *services.GetBeatResponse, _a1 error) *MockGetBeat_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetBeat_Exec_Call) RunAndReturn(run func(context.Context, *services.GetBeatRequest) (*services.GetBeatResponse, error)) *MockGetBeat_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetBeat creates a new instance of MockGetBeat. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetBeat(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetBeat {
	mock := &MockGetBeat{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
