// Code generated by mockery v2.46.3. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/a-novel/uservice-story-structure/pkg/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockBatchDeletePlotPoints is an autogenerated mock type for the BatchDeletePlotPoints type
type MockBatchDeletePlotPoints struct {
	mock.Mock
}

type MockBatchDeletePlotPoints_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchDeletePlotPoints) EXPECT() *MockBatchDeletePlotPoints_Expecter {
	return &MockBatchDeletePlotPoints_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, ids, creatorID
func (_m *MockBatchDeletePlotPoints) Exec(ctx context.Context, ids uuid.UUIDs, creatorID string) ([]*entities.PlotPoint, error) {
	ret := _m.Called(ctx, ids, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 []*entities.PlotPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUIDs, string) ([]*entities.PlotPoint, error)); ok {
		return rf(ctx, ids, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUIDs, string) []*entities.PlotPoint); ok {
		r0 = rf(ctx, ids, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.PlotPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUIDs, string) error); ok {
		r1 = rf(ctx, ids, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBatchDeletePlotPoints_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockBatchDeletePlotPoints_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - ids uuid.UUIDs
//   - creatorID string
func (_e *MockBatchDeletePlotPoints_Expecter) Exec(ctx interface{}, ids interface{}, creatorID interface{}) *MockBatchDeletePlotPoints_Exec_Call {
	return &MockBatchDeletePlotPoints_Exec_Call{Call: _e.mock.On("Exec", ctx, ids, creatorID)}
}

func (_c *MockBatchDeletePlotPoints_Exec_Call) Run(run func(ctx context.Context, ids uuid.UUIDs, creatorID string)) *MockBatchDeletePlotPoints_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUIDs), args[2].(string))
	})
	return _c
}

func (_c *MockBatchDeletePlotPoints_Exec_Call) Return(_a0 []*entities.PlotPoint, _a1 error) *MockBatchDeletePlotPoints_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBatchDeletePlotPoints_Exec_Call) RunAndReturn(run func(context.Context, uuid.UUIDs, string) ([]*entities.PlotPoint, error)) *MockBatchDeletePlotPoints_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBatchDeletePlotPoints creates a new instance of MockBatchDeletePlotPoints. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchDeletePlotPoints(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchDeletePlotPoints {
	mock := &MockBatchDeletePlotPoints{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
