// Code generated by mockery v2.46.0. DO NOT EDIT.

package daomocks

import (
	context "context"

	dao "github.com/a-novel/uservice-story-structure/pkg/dao"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSearchBeats is an autogenerated mock type for the SearchBeats type
type MockSearchBeats struct {
	mock.Mock
}

type MockSearchBeats_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchBeats) EXPECT() *MockSearchBeats_Expecter {
	return &MockSearchBeats_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, request
func (_m *MockSearchBeats) Exec(ctx context.Context, request *dao.SearchBeatsRequest) (uuid.UUIDs, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 uuid.UUIDs
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dao.SearchBeatsRequest) (uuid.UUIDs, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dao.SearchBeatsRequest) uuid.UUIDs); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUIDs)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dao.SearchBeatsRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSearchBeats_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockSearchBeats_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - request *dao.SearchBeatsRequest
func (_e *MockSearchBeats_Expecter) Exec(ctx interface{}, request interface{}) *MockSearchBeats_Exec_Call {
	return &MockSearchBeats_Exec_Call{Call: _e.mock.On("Exec", ctx, request)}
}

func (_c *MockSearchBeats_Exec_Call) Run(run func(ctx context.Context, request *dao.SearchBeatsRequest)) *MockSearchBeats_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*dao.SearchBeatsRequest))
	})
	return _c
}

func (_c *MockSearchBeats_Exec_Call) Return(_a0 uuid.UUIDs, _a1 error) *MockSearchBeats_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSearchBeats_Exec_Call) RunAndReturn(run func(context.Context, *dao.SearchBeatsRequest) (uuid.UUIDs, error)) *MockSearchBeats_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSearchBeats creates a new instance of MockSearchBeats. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchBeats(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchBeats {
	mock := &MockSearchBeats{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
