// Code generated by mockery v2.46.3. DO NOT EDIT.

package daomocks

import (
	context "context"

	entities "github.com/a-novel/uservice-story-structure/pkg/entities"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDeletePlotPoint is an autogenerated mock type for the DeletePlotPoint type
type MockDeletePlotPoint struct {
	mock.Mock
}

type MockDeletePlotPoint_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeletePlotPoint) EXPECT() *MockDeletePlotPoint_Expecter {
	return &MockDeletePlotPoint_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function with given fields: ctx, id, creatorID
func (_m *MockDeletePlotPoint) Exec(ctx context.Context, id uuid.UUID, creatorID string) (*entities.PlotPoint, error) {
	ret := _m.Called(ctx, id, creatorID)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *entities.PlotPoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*entities.PlotPoint, error)); ok {
		return rf(ctx, id, creatorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *entities.PlotPoint); ok {
		r0 = rf(ctx, id, creatorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.PlotPoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(ctx, id, creatorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeletePlotPoint_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockDeletePlotPoint_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - creatorID string
func (_e *MockDeletePlotPoint_Expecter) Exec(ctx interface{}, id interface{}, creatorID interface{}) *MockDeletePlotPoint_Exec_Call {
	return &MockDeletePlotPoint_Exec_Call{Call: _e.mock.On("Exec", ctx, id, creatorID)}
}

func (_c *MockDeletePlotPoint_Exec_Call) Run(run func(ctx context.Context, id uuid.UUID, creatorID string)) *MockDeletePlotPoint_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockDeletePlotPoint_Exec_Call) Return(_a0 *entities.PlotPoint, _a1 error) *MockDeletePlotPoint_Exec_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeletePlotPoint_Exec_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*entities.PlotPoint, error)) *MockDeletePlotPoint_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeletePlotPoint creates a new instance of MockDeletePlotPoint. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeletePlotPoint(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeletePlotPoint {
	mock := &MockDeletePlotPoint{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
